### ISSUE TITLE
Cannot send logs to App Insights with Spring Boot Log4j2 Starter + v3 Java Agent

### ISSUE THREAD

**Issue by Stephen-X** [microsoft/ApplicationInsights-Java#1424]
### Expected behavior
After adding the 3.0.0 GA Java Agent to the built Jar of my Spring Boot project w/ Log4j2, I expect it to automatically collect and send out console logs Log4j2 produces w/o any configurations, as claimed in the [documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#send-custom-traces-and-exceptions-using-your-favorite-logging-framework).

### Actual behavior
While the app is running, I can see metrics being fed to App Insights (checked Application Map and Live Metrics), but I can't see any logs on App Insights.

### Screenshots
No logs were ever sent to App Insights:

<img width="1680" alt="Screen Shot 2020-12-23 at 5 22 01 PM" src="https://user-images.githubusercontent.com/23654800/103057571-b1f31780-4554-11eb-9d2d-2ebc128f4289.png">

### To Reproduce
Please follow the README steps in the sample application linked below.

#### Sample Application
Here's a sample project to reproduce the issue, please follow the README instruction there: [Issue Demo: Spring Boot + Log4j2 + Azure App Insights](https://github.com/Stephen-X/appinsights-demo). The app simply logs a `Test task!` message every 5s.

### System information
Please provide the following information:
 - SDK Version: 3.0.0
 - OS type and version: Alpine 3.12, or whatever version the latest [AdoptOpenJDK Docker image](https://github.com/AdoptOpenJDK/openjdk-docker/blob/master/11/jdk/alpine/Dockerfile.hotspot.releases.full) is using
 - Application Server type and version (if applicable): Spring Boot 2.4.1
 - Using spring-boot? **Yes**
 - Additional relevant libraries (with version, if applicable): Log4j2 2.13.3 (Bundled with Spring Boot)

### Logs
With `selfDiagnostics.level` set to `TRACE`: [logs.txt](https://github.com/microsoft/ApplicationInsights-Java/files/5738015/logs.txt)

**Comment by trask** [comment]
hi @Stephen-X, thanks for posting a repro, it looks like you are using log4j async logging:

https://github.com/Stephen-X/appinsights-demo/blob/93714ff298a05497aa890e1b04d06a3919f7932e/src/main/java/com/example/demo/App.java#L22

so you have probably hit a bug (#1389) that was just fixed in the 3.0.1-BETA.2

**Comment by Stephen-X** [comment]
Hi @trask thanks for following up! I did suspect async logging before and tried disabling it (as you pointed out you need only to comment out [line 22](https://github.com/Stephen-X/appinsights-demo/blob/93714ff298a05497aa890e1b04d06a3919f7932e/src/main/java/com/example/demo/App.java#L22)), but it was still not sending out logs. So far I've tried:

| Logger | 3.0.0 GA | 3.0.1 Beta 2 |
| --- | --- | --- |
| Sync | Not printing out logs | Not printing out logs |
| Async | Not printing out logs | Not printing out logs |

Do you think there's a setup issue in my demo, or is there something else that might cause an issue?

**Comment by Stephen-X** [comment]
Hi @trask my apologies, it seems there were setup issues involved in this. We created a workspace-based AI initially but for some reason the logs weren't showing on the portal. Switching back to the classic resource mode solved the issue. I can confirm 3.0.1-beta.2 solves the async logger issue. Thank you for your attention!
